#!/bin/bash

source hooks/_conf

function docker_manifest_annotate() {

    DOCKER_ARCH="$1"
    DOCKER_PLATFORM_ARCH="$2"
    DOCKER_MANIFEST_ANNOTATE_ARGS="${DOCKER_REPO}:${DOCKER_ARCH}-${DOCKER_TAG} --os linux --arch ${DOCKER_PLATFORM_ARCH}"

    if [ "$#" -ge "3" ]; then
        DOCKER_PLATFORM_VAR="$3"
        DOCKER_MANIFEST_ANNOTATE_ARGS="${DOCKER_MANIFEST_ANNOTATE_ARGS} --variant ${DOCKER_PLATFORM_VAR}"
    fi

    docker manifest annotate "${DOCKER_REPO}:${DOCKER_TAG}" ${DOCKER_MANIFEST_ANNOTATE_ARGS}
}

DOCKER_PLATFORM_REPOS=""
for platform in ${DOCKER_PLATFORMS}; do
    DOCKER_PLATFORM_REPOS="${DOCKER_PLATFORM_REPOS} ${DOCKER_REPO}:${platform/:*/}-${DOCKER_TAG}"
done

DOCKER_PLATFORM_REPOS="${DOCKER_PLATFORM_REPOS:1}"

docker manifest create "${DOCKER_REPO}:${DOCKER_TAG}" ${DOCKER_PLATFORM_REPOS}

for platform in ${DOCKER_PLATFORMS}; do
    docker_manifest_annotate ${platform//:/ }
done

docker manifest push "${DOCKER_REPO}:${DOCKER_TAG}"
